= jDeploy IntelliJ IDEA Plugin

jDeploy is a Java Deployment Toolkit that creates installers for Java Desktop applications.

This plugin integrates jDeploy into IntelliJ IDEA. It provides a "New Project" wizard that provides plug-and-play project templates for Swing, JavaFX, and Codname One.

All templates include GitHub workflows to automatically generate installers for Windows, macOS, and Linux.

== Features

. New Project Wizard for Swing, JavaFX, and Codename One
. Open jDeploy Settings from project context menu

== Requirements

. IntelliJ IDEA 2021.1 or later

== Installation

Download the latest version of the plugin from https://github.com/shannah/jdeploy-intellij-plugin/releases[the releases page] and install it using the "Install Plugin from Disk" option in IntelliJ IDEA's plugin manager.

== Quick Start

=== Creating a new project

The "New Project" wizard will automatically create a GitHub project for your application.  Therefore, you will be asked to enter a GitHub token that has permission to create repositories.

See https://docs.github.com/en/enterprise-server@3.9/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens[GitHub's documentation] for more information on creating a GitHub token.

Select "File" > "New" > "Project" to open the "New Project" wizard.

image::https://github.com/shannah/jdeploy-intellij-plugin/assets/2677562/9a229730-32a8-4c85-bbca-1b8ee8bb9973[]

Then select "jDeploy" from the list of project types.

image::https://github.com/shannah/jdeploy-intellij-plugin/assets/2677562/c3515be6-bcda-4ebf-90e7-097aa970a8dc[]

Select your desired project template:

image::https://github.com/shannah/jdeploy-intellij-plugin/assets/2677562/df897538-4345-4e50-bf56-3f5864679f37[]

For the "GitHub user" you should select the user account under which the project repository should be created.  E.g. If you enter "shannah", then the repository will be created at `https://github.com/shannah/{{ project-name }}`.

For the GitHub token, you should paste your GitHub personal access token.

TIP: See https://docs.github.com/en/enterprise-server@3.9/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens[GitHub's documentation] for more information on creating a GitHub token.

If you check the "Private Repository" checkbox, then the repository will be created as a private repository, and a second, public, repository will be created for your releases.  This releases repository will be named `{{ repository-name }}-releases`, where `{{ repository-name }}` is the name of your project repository.

Click "Next" to continue.

The next step of the wizard is the standard IntelliJ IDEA "New Project" wizard.  You can enter your project name, location, etc... here.

Then click "Create" to create your project.

This will trigger the creation of your GitHub repository, and the creation of a GitHub workflow that will automatically build your project and create installers for Windows, macOS, and Linux.

The README file will include a link to the releases for your project.  It may take a couple of minutes for the release to be available, as it is generated by GitHub actions.

image::https://github.com/shannah/jdeploy-intellij-plugin/assets/2677562/09b9c1d5-f826-4e7d-9ecd-102586ca8962[]

Once the release is ready, you will see download links for the installers for Windows, macOS, and Linux on the GitHub releases page.

TIP: The releases are named after the branch that they were built from. They are automatically updated when a new commit is pushed to the branch.  Therefore, you can use the releases to distribute your application to testers, and they will automatically get the latest version when you push a new commit to the branch.

Tag releases are also supported.

image::https://github.com/shannah/jdeploy-intellij-plugin/assets/2677562/0521f884-bd64-4383-bfb7-b064943706fc[]

The following screenshots demonstrate the download and installation of the application on MacOS.

Clicking on the "Mac (Apple Silicon)" link will download the installer for Apple Silicon Macs.

image::https://github.com/shannah/jdeploy-intellij-plugin/assets/2677562/47f6faf9-f491-4ea0-9dde-50c023927077[]

When you first open the installer, you will be prompted to confirm that you want to open it.

NOTE: The application installer is signed by jDeploy's developer certificate.

image::https://github.com/shannah/jdeploy-intellij-plugin/assets/2677562/9f2885b7-512b-45bf-9d0a-faee37281dea[]

The installation wizard provides options to add the application to the Dock and to create a desktop shortcut.

image::https://github.com/shannah/jdeploy-intellij-plugin/assets/2677562/383f1a24-705a-48d3-91b1-6e816ea1c155[]

To prevent accidental installation of software you do not trust, the installer will prompt the user to confirm that this software is from a developer that they trust.

TIP: By default it displays the GitHub repository as the software homepage, but you can change this by setting the `homepage` property in the `jdeploy.properties` file.  If you do that, you'll need to verify your ownership of that domain.

image::https://github.com/shannah/jdeploy-intellij-plugin/assets/2677562/1ee75464-7426-4fb0-9843-9493349687d8[]

Once the installation is complete, the application will be launched, and, if the user chose to add it to the Dock, it will be added to the Dock.

image::https://github.com/shannah/jdeploy-intellij-plugin/assets/2677562/39601b4d-8316-439f-8ac5-a38bf172f6b1[]

image::https://github.com/shannah/jdeploy-intellij-plugin/assets/2677562/57c6d36e-f430-4399-b742-d882120354d3[]

The "Swing" template is a simple Hello World application, shown below.

image::https://github.com/shannah/jdeploy-intellij-plugin/assets/2677562/c0d2b594-af01-42fb-872d-033e78e3ad44[]

=== The jDeploy Settings Wizard

All of the jDeploy settings are contained in the package.json file in the root of the project.  You can either edit this file directly, or use the jDeploy settings wizard to edit it through a GUI.

To open the jDeploy settings wizard, right-click on the "Project" in the project explorer, and select "jDeploy Settings"

image::https://github.com/shannah/jdeploy-intellij-plugin/assets/2677562/687a49f2-edaf-4ece-a251-0e962946ee3d[]

This will open the wizard.  Make your changes, and click "Apply" to save them.

image::https://github.com/shannah/jdeploy-intellij-plugin/assets/2677562/3b9925a9-0da1-45c2-abb7-1149f5aa9df4[]

See https://www.jdeploy.com/docs/manual[the jDeploy manual] for more information on the settings.

